
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: go-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: "2"
          limits:
            memory: 1024Mi
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: go-app
  type: ClusterIP
