
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-app
  namespace: default
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-app
  template:
    metadata:
      labels:
        app: cs-app
    spec:
      containers:
      - name: cs-app
        image: dotnet-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: "2"
          limits:
            memory: 256Mi
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config
        configMap:
          name: cs-app
---
apiVersion: v1
kind: Service
metadata:
  name: cs-app
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: cs-app
  type: ClusterIP
